---
gpus: '0'
batch_size: 64
frequent: 50
kv_store: 'device'
memonger: False
retrain: False
model_path: './model/'
out_path: './outputs/infoGAN/'
model_load_epoch: 0
num_epoch: 100
network:
  ngf: 64
  ndf: 64
  dropout: False


train:
  lr: 0.0001
  beta1: 0.5
  wd: 0.0
  

dataset:
  data_type: 'mnist'
  n_rand: 100
  n_class: 10
  h: 64
  w: 64
  
  

